export CC=gcc
export CFLAGS="-O2 -g"

export SHELL=/bin/sh
export PAGER=less

export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;40:tw=

alias ls='ls --color=auto'
export EDITOR=vim

export PS1="\e[1;37m[\e[1;31m\u\e[1;37m:\e[1;33m\w\e[1;37m]$\e[m "
alias lsmod='modprobe -l'
alias less='less -d'

export GROFF_NO_SGR=1
